#! /bin/bash

ACTION=$1
PARAMS=$@
REST_PARAMS="${PARAMS[@]:$(echo -n $1 | wc -m)}"

declare -a ACTIONS_LIST=(
  start
  stop
  status
  restart
  createuser
  createdb
)

program() {
  if [[ $ACTION == "${ACTIONS_LIST[0]}" ]]; then
    pg_ctl -D /usr/local/var/postgres start
    return;
  fi

  if [[ $ACTION == "${ACTIONS_LIST[1]}" ]]; then
      pg_ctl -D /usr/local/var/postgres stop
    return;
  fi

  if [[ $ACTION == "${ACTIONS_LIST[2]}" ]]; then
      pg_ctl -D /usr/local/var/postgres status
    return;
  fi

  if [[ $ACTION == "${ACTIONS_LIST[3]}" ]]; then
      pg_ctl -D /usr/local/var/postgres restart
    return;
  fi

  if [[ $ACTION == "${ACTIONS_LIST[4]}" ]]; then
      /usr/local/Cellar/postgresql/13.2_1/bin/createuser$REST_PARAMS
    return;
  fi

    if [[ $ACTION == "${ACTIONS_LIST[4]}" ]]; then
      /usr/local/Cellar/postgresql/13.2_1/bin/createdb$REST_PARAMS
    return;
  fi

  echo '[ERROR] Not enough parameters.'
}

program
